### ISSUE TITLE
Adding kebab-case?

### ISSUE THREAD

**Issue by yahyaerturan** [huynhsamha/js-convert-case#10]
It's impressive work, thank you first of all.

Do you think to add add kebab-case ?

**Comment by huynhsamha** [comment]
Hi @yahyaerturan,

Sorry for my late reply, I will add this feature in the next release.

Thanks.

**Comment by HassanAkbar** [comment]
@huynhsamha will this release also cover Object keys conversion?

**Comment by huynhsamha** [comment]
Sorry for my late reply. Recently, I've not had more time to update this project.
I have just published a new version supports this issue.
Now you can update the version to [4.2.0](https://github.com/huynhsamha/js-convert-case/releases/tag/v4.2.0).
